WebApplication1/Pages/ListPassing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages
{
    public class ListPassingModel : PageModel
    {
        private readonly IPassingService _passingService;
        public List<Passing> bookings { get; set; }

        public ListPassingModel(IPassingService passingService)
        {
            _passingService = passingService;
        }
        public async Task<IActionResult> OnGetAsync(int? roomId, string? nameBooking, string? emailBooking, string? phoneBooking, DateTime? fromBooking, DateTime? toBooking)
        {
            // Danh sách booking của room id 
            bookings = await _passingService.PassingBookingsAvailableSearching(roomId, nameBooking, emailBooking, phoneBooking, fromBooking, toBooking);

            // Check if có phòng đã có người thuê thì không hiện danh sách booking
            bool isRoomRented = await _passingService.isRoomRented(roomId);
            ViewData["isRoomRented"] = isRoomRented;

            // Check if có phòng đã có đồng ý cho user thuê chỉ chờ bên admin duyệt
            bool isRoomWaiting = await _passingService.isRoomWaiting(roomId);
            ViewData["isRoomWaiting"] = isRoomWaiting;

            // search history 
            ViewData["roomId"] = roomId;
            ViewData["nameBooking"] = nameBooking;
            ViewData["emailBooking"] = emailBooking;
            ViewData["phoneBooking"] = phoneBooking;
            ViewData["fromBooking"] = fromBooking;
            ViewData["toBooking"] = toBooking;
            return Page();
        }
        // Gửi thông tin lịch hẹn cho từng user
        public async Task<IActionResult> OnPostAllUserAsync(DateTime? meetingdate, int? roomId)
        {
            await _passingService.UpdateMeetingDateAllUser(meetingdate, roomId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
        // Gửi thông tin lịch hẹn cho riêng user 
        public async Task<IActionResult> OnGetChangeMeetingAsync(DateTime? meetingDate, int? bookingId, int? roomId)
        {
            await _passingService.UpdateMeetingForUser(meetingDate, bookingId, roomId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
        // Set User to be Member 
        public async Task<IActionResult> OnGetSetMemberToRoomAsync(int roomId, int userId, int bookingId)
        {
            // set member to room
             await _passingService.PushUserToAdmin(userId, roomId, bookingId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
    }
}

WebApplication1/Pages/ListRoom.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Common;
using MotelManagement.Data.Models;
using System.Collections.Generic;

namespace MotelManagement.Pages
{
    public class ListRoomModel : PageModel
    {
        private readonly IRoomService _roomService;
        private readonly IRoomTypeService _roomTypeService;
        private readonly IContractService _contractService;

     //   Design : Hiện nút booking : 
     //   TH1 : room và user chưa nằm trong bảng booking
     //   TH2 : room và user nằm trong bảng booking nhưng trạng thái là status là 0 và không có trạng thái 1 (đã hủy booking trước đó ) 
        public bool isShowBooking(Room room, int userId)
        {
            if(room.Bookings == null)
               return true;
            else
            {
                Booking booking = room.Bookings.Where(b => b.UserId == userId && 
                                                           b.RoomId == room.RoomId && 
                                                           b.Status == (int)REGISTER_ROOM_STATE.REGISTER).FirstOrDefault();
                if (booking == null)
                    return true;
            }
            return false; 
        }
        public bool isShowCancelBooking(Room room, int userId)
        {
            if (room.Bookings == null)
                return false;
            Booking booking = room.Bookings.Where(b => b.UserId == userId &&
                                                           b.RoomId == room.RoomId &&
                                                           b.Status == (int)REGISTER_ROOM_STATE.REGISTER).FirstOrDefault();
            if (booking != null)
                return true;
            return false;
        }

        // Check nếu như là member của phòng này 
        public async Task<bool> isMemberOfRoom(Room room, int userId)
        {
            return await _contractService.isMemberOfRoom(room.RoomId, userId); 
        }

        public ListRoomModel(IRoomService roomService, IRoomTypeService roomTypeService, IContractService contractService)
        {
            _roomService = roomService;
            _roomTypeService = roomTypeService;
            _contractService = contractService; 
        }
        public async Task<IActionResult> OnGetAsync(string nameRoom, int? roomTypeId, int? status, string price, string sizePerson, int pageIndex)
        {
            // All RoomType 
            List<Status> statusList = new List<Status>();
            statusList.Add(new Status { StatusId = (int)ROOM_STATE.RENTED, Name = "Đã Thuê"} );
            statusList.Add(new Status { StatusId = (int)ROOM_STATE.PROCESSING, Name = "Còn Trống" });
            statusList.Add(new Status { StatusId = (int)ROOM_STATE.PASSING, Name = "Muốn Pass" });
            ViewData["statusList"] = statusList;

            // All RoomType 
            List<RoomType> roomTypes = await _roomTypeService.GetAll();
            ViewData["roomTypes"] = roomTypes;

            // Convert page 
            if(pageIndex <= 0)
                pageIndex = 1;

            // Advanced Search 
            List<Room> rooms = await _roomService.advancedSearchRoomList(nameRoom, roomTypeId, status, price, sizePerson, pageIndex);
 
            // Count để phân trang
            int totalPage = await _roomService.totalPage(nameRoom, roomTypeId, status, price, sizePerson);

            // Phần RECOMMENDED ( Lấy top 4 phòng còn trống có giá thấp nhất )
            List<Room> roomsRecommendeds = await _roomService.roomRecommended(); 

            // Lấy Url 
            // Lấy Url để phân trang cho avancedSearch 
            string url = "List?";
            string url_param = Request.QueryString.ToString();
            if (url_param != null && url_param.Length > 0)
            {
                url = "List";
                if (url_param.EndsWith("pageIndex=" + pageIndex))
                {
                    url_param = url_param.Replace("pageIndex=" + pageIndex, "");
                }
                // nếu nó không rời vào trường hợp book?page=x và thiếu & thì thêm vào
                if (!url_param.Equals("") && !url_param.EndsWith("&") && !url_param.EndsWith("?"))
                {
                    url_param += "&";
                }
                url += (url_param);
            }
            ViewData["url"] = url;
            ViewData["totalPage"] = totalPage;
            ViewData["pageIndex"] = pageIndex;
            ViewData["rooms"] = rooms;
            ViewData["roomsRecommendeds"] = roomsRecommendeds;
            // History Search 
            ViewData["nameRoom"] = nameRoom;
            ViewData["roomTypeId"] = roomTypeId;
            ViewData["status"] = status;
            ViewData["price"] = price;
            ViewData["sizePerson"] = sizePerson; 
            return Page();
        }
    }
}

WebApplication1/Pages/admin/AddNewArticelid.cshtml.cs
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages.admin
{
    public class AddNewArticelid : PageModel
    {
        private readonly IArticleService _service;
        private readonly MotelManagementContext _context;

        public AddNewArticelid(IArticleService userService, MotelManagementContext context, ILogger<LoginModel> logger)
        {
            this._service = userService;
            this._context = context;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(string header, string Content, List<IFormFile> fileimage)
        {
            ArticleRoom room = new ArticleRoom();
            room.header = header;
            room.Content = Content;
            foreach (var item in fileimage)
            {
                var FileName = $"{DateTime.Now:yyyyMMddHHmmss}_{Path.GetFileName(item.FileName)}";
                var filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload", FileName);
                using (var fileSrteam = new FileStream(filepath, FileMode.Create))
                {
                    await item.CopyToAsync(fileSrteam);
                }
                room.ImageArticle = FileName;
            }
            await _context.ArticleRoom.AddAsync(room);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Thêm tin tức thành công!";
            return Redirect("/admin/article/list");
        }
    }
}

WebApplication1/Pages/admin/AddNewRoom.cshtml.cs
using DocumentFormat.OpenXml.Drawing.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Business.Service;
using MotelManagement.Common;
using MotelManagement.Data.Models;
using System.Text.Json;

namespace MotelManagement.Pages.admin
{
    public class AddNewRoom : PageModel
    {
        private readonly IRoomService _service;
        private readonly IRoomTypeService _roomTypeService;
        private readonly ILogger<LoginModel> _logger;
        private readonly MotelManagementContext _context;
        public AddNewRoom(IRoomService userService , IRoomTypeService roomTypeService, MotelManagementContext context, ILogger<LoginModel> logger)
        {
            this._service = userService;
            this._roomTypeService = roomTypeService;    
            this._context = context;
            this._logger = logger; 
        }

        public async Task OnGetAsync()
        {
            List<RoomType> roomTypes = await _roomTypeService.GetAll();
            ViewData["roomTypes"] = roomTypes;
        }

        public async Task<IActionResult> OnPostAddnewAsync(string Name , string Description , decimal price , int MaxPerson , int RoomTypeId , List<IFormFile> fileimage)
        {
            try
            {
                Room room = new Room();
                room.Name = Name;
                room.Description = Description;
                room.Price = price;
                room.MaxPerson = MaxPerson;
                room.RoomTypeId = 1;
                room.StatusId = 2;
                Room tmp = await _service.AddNewRoom(room);
                foreach (var item in fileimage)
                {
                    var FileName = Path.GetFileName(item.FileName);
                    var filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload", FileName);
                    using (var fileSrteam = new FileStream(filepath, FileMode.Create))
                    {
                        await item.CopyToAsync(fileSrteam);
                    }
                    Image image = new Image();
                    image.Url = FileName;
                    image.RoomId = tmp.RoomId;
                    await _context.Images.AddAsync(image);
                }
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            TempData["Message"] = "Error";
            return Redirect("/admin/room/list");
        }
    }


    public class DataForRoom
    {
        public Room Room { get; set; }
        public List<IFormFile> Files { get; set; }
    }
}

WebApplication1/Pages/admin/AddNewRoomType.cshtml.cs
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages.admin
{
    public class AddNewRoomTypeModel : PageModel
    {
        private readonly IRoomTypeService _service;
        private readonly ILogger<LoginModel> _logger;
        public AddNewRoomTypeModel(IRoomTypeService userService, ILogger<LoginModel> logger)
        {
            this._service = userService;
            this._logger = logger;
        }

        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAddNewRoomTypeAsync(RoomType roomType)
        {
            _logger.LogDebug("da log duoc vao trong ham");
            try
            {
                await _service.AddNewRoomType(roomType);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            TempData["SuccessAddRoomTypeMessage"] = "Thêm loại phòng thành công!";
            return Redirect("/admin/room/listRoomType");
        }
    }
}

WebApplication1/Pages/admin/Dashboard.cshtml.cs
using DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MotelManagement.Data.Models;
using Newtonsoft.Json;

namespace MotelManagement.Pages.admin
{
    public class DashboardModel : PageModel
    {
        private readonly MotelManagementContext _context;

        public DashboardModel(MotelManagementContext context)
        {
            _context = context;
        }
        public class BarChartData
        {
            public string RoomTypeName { get; set; }
            public decimal TotalRevenue { get; set; }
        }

        public class ChartData
        {
            public string Label { get; set; } // Nhãn của dữ liệu
            public double Percentage { get; set; } // Phần trăm
            public int Count { get; set; } // Số lượng
        }

        public List<BarChartData> BarChartDatas { get; set; }
        public List<ChartData> PieChartDatas { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            BarChartDatas = await _context.Bills
                .Include(b => b.Room) // Kết hợp thông tin từ bảng Room
                 .ThenInclude(r => r.RoomType) // Kết hợp thông tin từ bảng RoomType
                .GroupBy(b => b.Room.RoomType.Name) // Nhóm theo tên của loại phòng
                .Select(group => new BarChartData
                {
                    RoomTypeName = group.Key, // Tên của loại phòng
                    TotalRevenue = group.Sum(b => b.RoomBill + b.ElectricBill + b.WaterBill + b.ServiceBill) // Tổng doanh số của loại phòng
                })
                .ToListAsync();

            var roomStatusCounts = await _context.Rooms
                .GroupBy(r => r.StatusId)
                .Select(group => new
                {
                    StatusId = group.Key,
                    Count = group.Count()
                })
                .ToListAsync();

            int totalRooms = roomStatusCounts.Sum(x => x.Count);

            var pieChartData = new List<ChartData>();
            foreach (var statusCount in roomStatusCounts)
            {
                string statusName = "";
                switch (statusCount.StatusId)
                {
                    case 1:
                        statusName = "Đã thuê";
                        break;
                    case 2:
                        statusName = "Còn trống";
                        break;
                    case 3:
                        statusName = "Cần Pass";
                        break;
                        // Thêm các trạng thái khác nếu cần
                }

                // Tính phần trăm và số lượng
                double percentage = (double)statusCount.Count / totalRooms * 100;

                pieChartData.Add(new ChartData
                {
                    Label = statusName,
                    Percentage = Math.Round(percentage, 2), // Làm tròn phần trăm đến 2 chữ số thập phân
                    Count = statusCount.Count
                });

                PieChartDatas = pieChartData;
            }

            return Page();
        }
    }
}

WebApplication1/Pages/admin/ListArticleRoom.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MotelManagement.Business.IService;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages.admin
{
    public class ListArticleRoomModel : PageModel
    {
        public readonly IArticleService _control;
        public MotelManagementContext _context;

        public ListArticleRoomModel(IArticleService _service, MotelManagementContext context)
        {
            this._control = _service;
            this._context = context;

        }
        public async Task<IActionResult> OnGetAsync()
        {

            //List<ArticleRoom> data = await _control.GetListArticleRooms();
            List<ArticleRoom> data = await _context.ArticleRoom.ToListAsync();
            ViewData["lstArticleRoom"] = data;
            return Page();
        }

    }
}

WebApplication1/Pages/admin/AddNewArticelid.cshtml
@page "/admin/article/addnew"
@model MotelManagement.Pages.admin.AddNewArticelid
@{
}
<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container" style="padding: 30px; margin-top:40px">

        <div class="col-md-6" style="width:50%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 register-blocks">
                    <h2 class="text-center">Thêm tin tức mới </h2>
                    <form method="post" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="@ViewData["id"]">
                        <div class="form-group">
                            <label>Nhập tiêu đề</label>
                            <input type="text" class="form-control" name="header">
                        </div>
                        <div class="form-group">
                            <label>Chọn ảnh phòng</label>
                            <input type="file" class="form-control" name="fileimage" multiple>
                        </div>
                        <div class="form-group">
                            <label>Nội dung</label>
                            <textarea class="form-control" name="Content" rows="15"></textarea>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-outline-success">Thêm mới</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/Pages/admin/AddNewRoom.cshtml
@page "/admin/room/addnew"
@using MotelManagement.Data.Models
@model MotelManagement.Pages.admin.AddNewRoom
@{
}
<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container" style="padding: 30px; margin-top:40px">
        
        <div class="col-md-6" style="width:50%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 register-blocks">
                    <h2 class="text-center">Thêm phòng mới </h2>
                    <form method="post" asp-page-handler="Addnew" enctype="multipart/form-data">
                        <div class="form-group">
                            <label >Nhập tên phòng</label>
                            <input type="text" class="form-control" name="Name">
                        </div>
                        <div class="form-group">
                            <label>Miêu tả phòng</label>
                            <input type="text" class="form-control" name="Description">
                        </div>
                        <div class="form-group">
                            <label>Giá phòng</label>
                            <input type="number" class="form-control" name="Price">
                        </div>
                        <div class="form-group">
                            <label>Số người tối đa</label>
                            <input type="text" class="form-control" name="MaxPerson">
                        </div>
                        <div class="form-group">
                            <label>Kiểu phòng</label>
                            <select class="form-control" name="RoomTypeId">
                                @foreach (RoomType roomType in (List<RoomType>)@ViewData["roomTypes"])
                                {
                                    if (roomType.RoomTypeId == Convert.ToInt32(ViewData["roomTypeId"]))
                                    {
                                        <option selected="selected" value="@roomType.RoomTypeId">@roomType.Name</option>
                                    }
                                    else
                                    {
                                        <option value="@roomType.RoomTypeId">@roomType.Name</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Chọn ảnh phòng</label>
                            <input type="file" class="form-control" name="fileimage" multiple>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-outline-success">Thêm mới</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/Pages/admin/AddNewRoomType.cshtml
@page "/admin/room/addnewroomtype"
@model MotelManagement.Pages.admin.AddNewRoomTypeModel
@{

}

<div class="container" style="padding:50px">
    <h1>      </h1>
    <h1>      </h1>
    <h1>      </h1>
    <div class="col-md-6">
        <div class="box-for overflow">
            <div class="col-md-12 col-xs-12 register-blocks">
                <h2>Thêm mới kiểu phòng </h2>
                <form method="post" asp-page-handler="AddNewRoomType">
                    <div class="form-group">
                        <label for="Name">Tên kiểu phòng</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-outline-success">Thêm mới kiểu phòng</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WebApplication1/Pages/admin/DeleteArticelid.cshtml
@page "/admin/Article/delete/{id:int}"
@model MotelManagement.Pages.admin.DeleteArticelidModel
@{
}

<h1>Xóa tin tức thành công</h1>

WebApplication1/Pages/admin/DeleteRoomType.cshtml
@page "/admin/room/listroomtype/delete/{id:int}"
@model MotelManagement.Pages.admin.DeleteRoomTypeModel
@{
}

<h1>Xóa loại phòng thành công</h1>

WebApplication1/Pages/admin/ListBooking.cshtml
@page "/admin/room/booking/list"
@using MotelManagement.Data.Models
@model MotelManagement.Pages.admin.ListBookingModel
@{
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <div class="mt-5">
                @if (Model.bookings != null && Model.bookings.Count > 0)
                {
                    <h4 class="card-title float-left mt-2">Danh Sách Booking: <span style="color : red">@Model.bookings.ElementAt(0).Room.Name</span></h4>
                    <form method="post" asp-page-handler="AllUser" class="float-right">
                        <td><input type="datetime-local" name="meetingdate" /></td>
                        <td><input hidden="hidden" type="text" name="roomId" value="@Model.bookings.ElementAt(0).Room.RoomId" /></td>
                        <td><button class="btn btn-success veiwbutton ">Hẹn Tất Cả User</button></td>
                    </form>
                }
            </div>
        </div>
    </div>
</div>
@if ((bool)ViewData["isRoomRented"] == true)
{
    <h3 class = "align-items-center" style="color : red">Phòng đang có người thuê - không có danh sách booking</h3>
}
<div class="row">
    <div class="col-lg-12">
        <form action = "/admin/room/booking/list" method = "Get">
            <input type ="hidden" name = "roomId" value = "@ViewData["roomId"]"/>
            <div class="row formtype">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Tên Người Booking</label>
                        <input class="form-control" name = "nameBooking" type="text" value="@ViewData["nameBooking"]" placeholder = "Search Theo Tên" >
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" name = "emailBooking" type="text" value="@ViewData["emailBooking"]" placeholder = "Search Theo Email" >
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Phone</label>
                        <input class="form-control" name = "phoneBooking" type="text" value="@ViewData["phoneBooking"]" placeholder = "Search Theo Phone" >
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>From Date Booking</label>
                        <div class="cal-icon">
                            <input type="text" name = "fromBooking" value = "@ViewData["fromBooking"]" class="form-control datetimepicker">
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>To Date Booking</label>
                        <div class="cal-icon">
                            <input type="text" name = "toBooking" value = "@ViewData["toBooking"]" class="form-control datetimepicker">
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Search</label>
                        <button class = "btn btn-info m-t-0 btn-block search_button"> Search </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body booking_card">
                <div class="table-responsive">
                    <table class="table table-stripped table table-hover table-center mb-0">
                        <thead>
                            <tr>
                                <th>Người Booking</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Booking Time</th>
                                <th>Meeting Date</th>
                                <th>Xác nhận cho thuê</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.bookings != null)
                            {
                                @foreach (Booking booking in Model.bookings)
                                {
                                    <tr>
                                        <td>@booking.User.FullName</td>
                                        <td>@booking.User.Email</td>
                                        <td>@booking.User.Phone</td>
                                        <td>@booking.BookingTime</td>
                                        <td><input onchange="ChangeTimeMeeting(this.value ,@booking.BookingId,@booking.RoomId)" type="datetime-local" name="meetingdate" value="@booking.MeetingDate?.ToString("yyyy-MM-ddTHH:mm")" /></td>
                                        <td><a href="/admin/room/booking/list?handler=SetMemberToRoom&roomId=@booking.RoomId&userId=@booking.UserId&price=@booking.Room.Price&bookingId=@booking.BookingId" id="SetMemberToRoom" class="btn btn-success veiwbutton ">Đồng ý</a></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
<script>
       function ChangeTimeMeeting(meetingDate, bookingId, roomId){
            console.log("a");
            window.location.href = "/admin/room/booking/list?handler=ChangeMeeting&meetingDate="+meetingDate+"&bookingId="+bookingId+"&roomId="+roomId;
       }

       if(document.querySelector("#SetMemberToRoom")!=null){
        [document.querySelector("#SetMemberToRoom")].forEach(
        (item) => {
            item.addEventListener("click", (event) => {
                event.preventDefault();
                swal({
                    title: "Cho người này thuê phòng?",
                    text: "Tất cả booking sẽ bị hủy nếu đã có người thuê phòng!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location.href = item.href;
                    }
                });
            })
        }
    )
    }

        @{
            if (TempData["Message"] != null)
            {
                if (TempData["Message"].Equals("Success"))
                {
                            <text>
                                swal({
                                    title: "Cập nhật thành công!",
                                    text: "",
                                    icon: "success",
                                    buttons: false
                                });
                            </text>
                }
                else if(TempData["Message"].Equals("Probs"))
                {
                            <text>
                                swal({
                                    title: "Cập nhật thất bại!",
                                    text: "Opps! Đã có lỗi xảy ra!",
                                    icon: "warning",
                                    buttons: false
                                })
                            </text>
               }else if(TempData["Message"].Equals("Registered"))
               {
                            <text>
                                swal({
                                    title: "Cập nhật thất bại!",
                                    text: "Phòng này bạn đã đăng kí",
                                    icon: "warning",
                                    buttons: false
                                })
                            </text>
               }
        }
    }
</script>
}