WebApplication1/Pages/ChangeInfo.cshtml.cs
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MotelManagement.Business.IService;
using MotelManagement.Common;
using MotelManagement.Data.Models;
using System.Text.Json;

namespace MotelManagement.Pages
{
    public class ChangeInfoModel : PageModel
    {
        [BindProperty]
        public string ErrorMessage { get; set; }
        private readonly MotelManagementContext _context;
        private readonly IUserService _service;
        private readonly ILogger<ChangePasswordModel> _logger;
        public ChangeInfoModel(IUserService userService, ILogger<ChangePasswordModel> logger, MotelManagementContext context)
        {
            this._service = userService;
            this._logger = logger;
            _context = context;

        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostChangeInfoAsync(string fullName, string email, bool gender, string phone, string address, DateTime dob, string confirmPassword)
        {
            string json = HttpContext.Session.GetString("user");
            Console.WriteLine(json);
            if (json == null)
            {
                TempData["Message"] = "Failed";
                return Page();
            }
            else
            {
                User user = (User)JsonUtil.DeserializeObject<User>(json);
                if (user.Email.Equals(email) || user.Phone.Equals(phone))
                {
                    ErrorMessage = "Email / SĐT này đã được đăng ký, hãy sử dụng cái khác";
                    return Page();
                }
                else if (user.Password.Equals(confirmPassword))
                {
                    try
                    {
                        user.FullName = fullName;
                        user.Email = email;
                        user.Gender = gender;
                        user.Phone = phone;
                        user.Address = address;
                        user.Dob = dob;
                        await _service.ChangeInfo(user);
                        TempData["Message"] = "SuccChangeInfo";
                        return Redirect("../user/logout");
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex.ToString());
                    }
                }
                else 
                {
                    ErrorMessage = "Lỗi! Kiểm tra lại mật khẩu của bạn";
                    return Page();
                }
            }
            TempData["Message"] = "Wrong";
            return Page();

        }
    }
}

WebApplication1/Pages/ChangePassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Common;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages
{
    public class ChangePasswordModel : PageModel
    {
        private readonly IUserService _service;
        private readonly ILogger<ChangePasswordModel> _logger;
        public ChangePasswordModel(IUserService userService, ILogger<ChangePasswordModel> logger)
        {
            this._service = userService;
            this._logger = logger;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostChangepwAsync(string oldPassword, string password, string confirmPassword) {
            string json = HttpContext.Session.GetString("user");
            Console.WriteLine(json);
            if (json == null|| !password.Equals(confirmPassword))
            {
                TempData["Message"] = "Failed";
                return Page();
            }
            else
            {
                User user = (User)JsonUtil.DeserializeObject<User>(json);
                if (user.Password.Equals(oldPassword))
                {
                    try
                    {
                        user.Password = password;
                        await _service.ChangePasswordAync(user);
                        TempData["Message"] = "SuccChangePw";
                        return RedirectToPage("./homepage");
                    }
                    catch(Exception ex)
                    {
                        _logger.LogError(ex.ToString());
                    }
                }               
            }
            TempData["Message"] = "Wrong";
            return Page();
        }    
    }
}

WebApplication1/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages
{
    public class ContactModel : PageModel
    {
        private readonly MotelManagement.Data.Models.MotelManagementContext _context;

        public ContactModel(MotelManagement.Data.Models.MotelManagementContext context)
        {
            _context = context;
        }

    }
}

WebApplication1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MotelManagement.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication1/Pages/ListPassing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages
{
    public class ListPassingModel : PageModel
    {
        private readonly IPassingService _passingService;
        public List<Passing> bookings { get; set; }

        public ListPassingModel(IPassingService passingService)
        {
            _passingService = passingService;
        }
        public async Task<IActionResult> OnGetAsync(int? roomId, string? nameBooking, string? emailBooking, string? phoneBooking, DateTime? fromBooking, DateTime? toBooking)
        {
            // Danh sách booking của room id 
            bookings = await _passingService.PassingBookingsAvailableSearching(roomId, nameBooking, emailBooking, phoneBooking, fromBooking, toBooking);

            // Check if có phòng đã có người thuê thì không hiện danh sách booking
            bool isRoomRented = await _passingService.isRoomRented(roomId);
            ViewData["isRoomRented"] = isRoomRented;

            // Check if có phòng đã có đồng ý cho user thuê chỉ chờ bên admin duyệt
            bool isRoomWaiting = await _passingService.isRoomWaiting(roomId);
            ViewData["isRoomWaiting"] = isRoomWaiting;

            // search history 
            ViewData["roomId"] = roomId;
            ViewData["nameBooking"] = nameBooking;
            ViewData["emailBooking"] = emailBooking;
            ViewData["phoneBooking"] = phoneBooking;
            ViewData["fromBooking"] = fromBooking;
            ViewData["toBooking"] = toBooking;
            return Page();
        }
        // Gửi thông tin lịch hẹn cho từng user
        public async Task<IActionResult> OnPostAllUserAsync(DateTime? meetingdate, int? roomId)
        {
            await _passingService.UpdateMeetingDateAllUser(meetingdate, roomId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
        // Gửi thông tin lịch hẹn cho riêng user 
        public async Task<IActionResult> OnGetChangeMeetingAsync(DateTime? meetingDate, int? bookingId, int? roomId)
        {
            await _passingService.UpdateMeetingForUser(meetingDate, bookingId, roomId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
        // Set User to be Member 
        public async Task<IActionResult> OnGetSetMemberToRoomAsync(int roomId, int userId, int bookingId)
        {
            // set member to room
             await _passingService.PushUserToAdmin(userId, roomId, bookingId);
            return Redirect("/user/room/passing/list?roomId=" + roomId);
        }
    }
}

WebApplication1/Pages/Login.cshtml.cs
using DocumentFormat.OpenXml.EMMA;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Common;
using MotelManagement.Data.Models;
using System.Text.Json;

namespace MotelManagement.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string ErrorMessage { get; set; }
        private readonly IUserService _service;
        private readonly ILogger<LoginModel> _logger;
        public LoginModel(IUserService userService, ILogger<LoginModel> logger)
        {
            this._service = userService;
            this._logger = logger;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLoginAsync(string email, string password)
        {
            try
            {
                if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
                {
                    ErrorMessage = "Vui lòng nhập đủ thông tin.";
                    return Page();
                }

                User user = await _service.Login(email, password);

                if (user != null)
                {
                    string json = JsonUtil.SerializeObject(user);
                    HttpContext.Session.SetString("user", json);

                    if (user.RoleName != null)
                    {
                        return Redirect("~/admin/dashboard");
                    }

                    return Redirect("~/room/list");

                }
                else
                {
                    ErrorMessage = "Tên đăng nhập hoặc mật khẩu không đúng. Vui lòng thử lại.";
                    return Page();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            TempData["Message"] = "Error";
            return Redirect("~/errors");

        }
    }
}

WebApplication1/Pages/MyListRoom.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MotelManagement.Business.IService;
using MotelManagement.Common;
using MotelManagement.Data.Models;

namespace MotelManagement.Pages
{

    public class MyListRoomModel : PageModel
    {
        private readonly IBookingService _serviceBooking;
        private readonly IPassingService _servicePassingService;
        private readonly IContractService _serviceContract;
        private readonly IRoomService _serviceRoom;
        private readonly ILogger<LoginModel> _logger;
        public MyListRoomModel(IBookingService bookingService, ILogger<LoginModel> logger, IContractService contractService, IRoomService serviceRoom, IPassingService passingService)
        {
            this._serviceBooking = bookingService;
            _servicePassingService = passingService;
            this._serviceContract = contractService;
            _serviceRoom = serviceRoom; 
            this._logger = logger;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            string json = HttpContext.Session.GetString("user");
            User user = UserUtil.getUserFromSession(json);
            if (user != null)
            {
                try
                {
                    List<Booking> list = await _serviceBooking.listBookings(user.UserId);
                    List<Contract> listContracts = await _serviceContract.getListContractsByUserId(user.UserId);
                    List<Passing> listPassings = await _servicePassingService.GetListPassings(user.UserId);
                    ViewData["list"] = list;
                    ViewData["listPassings"] = listPassings;
                    ViewData["listContracts"] = listContracts;
                    return Page();
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                }
            }
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnGetUnregisterAsync(int roomid)
        {

            string json = HttpContext.Session.GetString("user");
            User user = UserUtil.getUserFromSession(json);
            if (user != null)
            {
                try
                {
                    bool isExist = await _serviceBooking.isBooking(roomid, user.UserId);
                    if(isExist&&roomid!=null)
                    {
                        await _serviceBooking.updateUnRegister(user.UserId, roomid);
                        TempData["Message"] = "Success";
                    }
                    else
                    {
                        TempData["Message"] = "Probs";
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                    TempData["Message"] = "Probs";
                }
            }
            return Redirect("~/user/mylistroom");
        }

        public async Task<IActionResult> OnGetUnregisterPassingAsync(int roomid)
        {

            string json = HttpContext.Session.GetString("user");
            User user = UserUtil.getUserFromSession(json);
            if (user != null)
            {
                try
                {
                    bool isExist = await _servicePassingService.isPassing(roomid, user.UserId);
                    if (isExist && roomid != null)
                    {
                        await _servicePassingService.UpdateUnregisterPassing(user.UserId, roomid);
                        TempData["Message"] = "Success";
                    }
                    else
                    {
                        TempData["Message"] = "Probs";
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                    TempData["Message"] = "Probs";
                }
            }
            return Redirect("~/user/mylistroom");
        }



        // Thành 
        public async Task<IActionResult> OnGetRegisterAsync(int roomid)
        {
            string json = HttpContext.Session.GetString("user"); 
            User user = UserUtil.getUserFromSession(json);
            if (user != null)
            {
                try
                {
                    bool isExist = await _serviceBooking.isBooking(roomid, user.UserId);
                    // TH user dùng url, nếu phòng đã có nguời đang có người thuê nhưng vẫn booking
                    Room room = await _serviceRoom.getRoomById(roomid);
                    if (!isExist && roomid != null && room.StatusId == (int)ROOM_STATE.PROCESSING)
                    {
                        await _serviceBooking.Register(user.UserId, roomid);
                        TempData["Message"] = "Success";
                    }
                    else if(isExist)
                    {
                        TempData["Message"] = "Registered";
                    }
                    else
                    {
                        TempData["Message"] = "Probs";
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                    TempData["Message"] = "Probs";
                }
            }
            return Redirect("~/user/mylistroom");
        }
        // Thành - Đăng kí Passing
        public async Task<IActionResult> OnGetRegisterPassingAsync(int roomId)
        {
            // Cần RoomId, MemberId, UserRequest 
            string json = HttpContext.Session.GetString("user");
            User user = UserUtil.getUserFromSession(json);
            if (user != null)
            {
                try
                {
                    // Phải check thêm nữa là nếu như là member thì không được đặt phòng đó
                    bool isMemberOfRoom = await _serviceContract.isMemberOfRoom(roomId, user.UserId);

                    // TH user dùng url, nếu phòng đã có nguời đang có người thuê nhưng vẫn booking passing
                    bool isExist = await _servicePassingService.isBookingPassing(roomId, user.UserId);
                    // Check xem room tồn tại không
                    Room room = await _serviceRoom.getRoomById(roomId);

                    if (!isMemberOfRoom && !isExist && roomId != null && room.StatusId == (int)ROOM_STATE.PASSING)
                    {
                        await _servicePassingService.RegisterPassing(user.UserId, roomId);
                        TempData["Message"] = "Success";
                    }
                    else if (isExist)
                    {
                        TempData["Message"] = "Registered";
                    }
                    else
                    {
                        TempData["Message"] = "Probs";
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                    TempData["Message"] = "Probs";
                }
            }
            return Redirect("~/user/mylistroom");
        }

    }
}

WebApplication1/Pages/ChangeInfo.cshtml
@page "/user/changeinfo"
@model MotelManagement.Pages.ChangeInfoModel
@{
}

<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Sửa thông tin tài khoản </h1>
            </div>
        </div>
    </div>
</div>

<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container">

        <div class="" style="width:80%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 register-blocks">

                    <div class="text-center">
                        <h2> Sửa lại thông tin </h2>
                    </div>
                    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                    {
                        <div class="alert alert-danger" role="alert">
                            @Model.ErrorMessage
                        </div>
                    }
                    <form asp-page-handler="ChangeInfo" onsubmit="return ValidateForm()" method="post">
                        <div class="form-group">
                            <label for="FullName">Họ Và Tên</label>
                            <input type="text" class="form-control" id="fullname" name="fullName">
                        </div>
                        <div class="form-group">
                            <label for="Email">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="form-group">
                            <label for="Gender">Giới tính</label>
                            <div style="display:flex; justify-content:center">
                                <div style="padding: 0px 32px 0px 0px">
                                    <label for="true">Nam</label>
                                    <input type="radio" style="padding-right:40px" class="form-control" name="gender" value="True" checked="checked">
                                </div>
                                <div>
                                    <label for="false">Nữ</label>
                                    <input type="radio" class="form-control" name="gender" value="False">
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="Phone">Số Điện Thoại</label>
                            <input type="number" id="phonenumber" class="form-control" name="phone">
                        </div>
                        <div class="form-group">
                            <label for="Address">Địa Chỉ</label>
                            <input type="text" id="address" class="form-control" name="address">
                        </div>
                        <div class="form-group">
                            <label for="Dob">Ngày Sinh</label>
                            <input type="date" id="Birthday" class="form-control" name="dob">
                        </div>
                        <div class="form-group">
                            <label for="Password">Mật Khẩu Hiện Tại</label>
                            <input type="password" id="password" class="form-control" name="confirmPassword">
                        </div>
                        <div class="text-center" style="margin-top: 40px">
                            <button type="submit" class="btn btn-default">Cập Nhật</button>
                        </div>
                        <br>
                        <br>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

<script>


    function ValidateForm() {
        var fullname = document.getElementById('fullname').value
        var email = document.getElementById('email').value
        var password = document.getElementById('password').value
        var phonenumber = document.getElementById('phonenumber').value
        var address = document.getElementById('address').value
        var Birthday = document.getElementById('Birthday').value
        console
        if (fullname === '' || email === '' || password === '' || phonenumber === '' || address === '' || Birthday === '') {
            console.log(" da log duoc vao trong ham");
            alert("Bạn điền thiếu thông tin rồi, hãy kiểm tra lại nhé!");
            return false;
        }

        else return true;
    }

</script>

WebApplication1/Pages/ForgetPassword.cshtml
@page "/user/forgetpassword"
@model MotelManagement.Pages.ForgetPasswordModel
@{
}


<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Quên mật khẩu </h1>
            </div>
        </div>
    </div>
</div>
<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container">
        <div class="" style="width:50%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 login-blocks">
                    <div class="text-center">
                        <h2> Gửi mã đăng nhập </h2>
                    </div>

                    <form method="post" asp-page-handler="ForgetPassword">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="text-center" style="margin-top: 40px">
                            <button type="submit" class="btn btn-default" onclick="alert('Mật khẩu đã được gửi về email, vui lòng kiểm tra!')">Gửi mã</button>
                        </div>
                        <div class="">
                            <button type="button" class="btn btn-link" style="margin: 0 auto; width:100%" onclick="location.href = '/user/login'">Trở về trang đăng nhập</button>
                            <button type="button" class="btn btn-link" style="margin: 0 auto; width:100%" onclick="location.href = '/user/register'">Tạo tài khoản mới</button>
                        </div>

                    </form>
                    <br>
                </div>

            </div>
        </div>
    </div>
</div>

WebApplication1/Pages/Login.cshtml
@page "/user/login"
@model MotelManagement.Pages.LoginModel
@{
}
<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Đăng nhập tài khoản </h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->
<!-- register-area -->
<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container">

        <div class="" style="width:80%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 login-blocks">
                    <div class="text-center">
                        <h2> Đăng nhập </h2>
                    </div>
                    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                    {
                        <div class="alert alert-danger" role="alert">
                            @Model.ErrorMessage
                        </div>
                    }
                    <form method="post" asp-page-handler="Login">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" autofocus>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="text-center" style="margin-top: 40px">
                            <button type="submit" class="btn btn-default"> Đăng Nhập</button>
                        </div>
                        <div class="">
                            <button type="button" class="btn btn-link" style="margin: 0 auto; width:100%" onclick="location.href = '/user/register'">Chưa có tài khoản? Đăng ký ngay!</button>
                            <button type="button" class="btn btn-link" style="margin: 0 auto; width:100%" onclick="location.href = '/user/forgetpassword'">Quên mật khẩu</button>
                        </div>
                    </form>
                    <br>
                </div>

            </div>
        </div>

    </div>
</div>

WebApplication1/Pages/Logout.cshtml
@page  "/user/logout"
@model MotelManagement.Pages.LogoutModel
@{
}

WebApplication1/Pages/Register.cshtml
@page "/user/register"
@model MotelManagement.Pages.RegisterModel
@using MotelManagement.Data.Models
@{
}

<div class="page-head">
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Đăng ký tài khoản </h1>
            </div>
        </div>
    </div>
</div>
<!-- End page header -->
<!-- register-area -->
<div class="register-area" style="background-color: rgb(249, 249, 249);">
    <div class="container">

        <div class="" style="width:80%; margin:0 auto">
            <div class="box-for overflow">
                <div class="col-md-12 col-xs-12 register-blocks">

                    <div class="text-center">
                        <h2> Đăng ký </h2>
                    </div>
                    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                    {
                        <div class="alert alert-danger" role="alert">
                            @Model.ErrorMessage
                        </div>
                    }
                    @* asp-page-handler="Register" *@
                    <form method="post" onsubmit="return ValidateForm()" asp-page-handler="Register">
                        <div class="form-group">
                            <label for="FullName">Họ Và Tên</label>
                            <input type="text" class="form-control" id="fullname" name="FullName">
                        </div>
                        <div class="form-group">
                            <label for="Email">Email</label>
                            <input type="email" class="form-control" id="email" name="Email">
                        </div>
                        <div class="form-group">
                            <label for="Gender">Giới tính</label>
                            <div style="display:flex; justify-content:center">
                                <div style="padding: 0px 32px 0px 0px">
                                    <label for="true">Nam</label>
                                    <input type="radio" style="padding-right:40px" class="form-control" name="gender" value="True" checked="checked">
                                </div>
                                <div>
                                    <label for="false">Nữ</label>
                                    <input type="radio" class="form-control" name="gender" value="False">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Password">Mật Khẩu</label>
                            <input type="password" id="password" class="form-control" name="Password">
                        </div>
                        <div class="form-group">
                            <label for="Phone">Số Điện Thoại</label>
                            <input type="number" id="phonenumber" class="form-control" name="Phone">
                        </div>
                        <div class="form-group">
                            <label for="Address">Địa Chỉ</label>
                            <input type="text" id="address" class="form-control" name="Address">
                        </div>
                        <div class="form-group">
                            <label for="Dob">Ngày Sinh</label>
                            <input type="date" id="Birthday" class="form-control" name="Dob">
                        </div>
                        <div class="text-center" style="margin-top: 40px">
                            <button type="submit" class="btn btn-default">Đăng Ký</button>
                        </div>
                        <div class="">
                            <button type="button" class="btn btn-link" style="margin: 0 auto; width:100%" onclick="location.href = '/user/login'">Đã có tài khoản? Đăng nhập ngay!</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

<script>


    function ValidateForm() {
        var fullname = document.getElementById('fullname').value
        var email = document.getElementById('email').value
        var password = document.getElementById('password').value
        var phonenumber = document.getElementById('phonenumber').value
        var address = document.getElementById('address').value
        var Birthday = document.getElementById('Birthday').value
        console
        if (fullname === '' || email === '' || password === '' || phonenumber === '' || address === '' || Birthday === '') {
            console.log(" da log duoc vao trong ham");
            alert("Bạn điền thiếu thông tin rồi, hãy kiểm tra lại nhé!");
            return false;
        }
        
        else return true;
    }

    function CallService() {
        let params = (new URL(document.location)).searchParams;
        window.location.href = "/user/register?handler=ExportBill&" + params;
    }

</script>